language: node_js
node_js:
  - "0.10"

branches:
  only:
        - master
services:
  - mongodb
before_script:
  - mongo blog --eval 'db.addUser("travis", "test");
notifications:
  email:
        - 18985551726@163.com